name: Auto Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Write version file into Laravel
        run: |
          echo "<?php return ['version' => '${VERSION}'];" > config/version.php

      - name: Commit version file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add config/version.php
          git commit -m "Auto version update ${VERSION}" || exit 0
          git push